### ISSUE TITLE
论文给的链接中并没有语音数据

### ISSUE THREAD

**Issue by blx0102** [athena-team/DidiSpeech#4]
目前还都是出行数据的申请

**Comment by Guo-T-W** [comment]
我们将会在10月24日的SLIMTS2020 Workshop (https://outreach.didichuxing.com/internationalconference/interspeech2020/ )上开放500人(挑选自DiDiSpeech-1)的语音数据至https://outreach.didichuxing.com/research/opendata/en。 此外，完整的DiDiSpeech语音数据库也将会逐步开放。

**Comment by blx0102** [comment]
@Guo-T-W 好的，感谢滴滴团队的贡献

**Comment by dragen1860** [comment]
@Guo-T-W 请问下DidiSpeech还是无法下载，可以提供一下信息如何下载数据集吗？谢谢。

**Comment by dragen1860** [comment]
@blx0102 你下载了数据集吗，可以加个微信交流不：dragen1860，谢谢。

**Comment by cnlinxi** [comment]
无法下载，期待更新下载链接
